
name: react-project

services:
  postgres:
    container_name: 'react-project-postgres'
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-harris}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-harris}
      POSTGRES_DB: ${POSTGRES_DB:-todo}
      TIMEZONE: ${TIMEZONE:-Europe/London}
    ports:
      - "${POSTGRES_PORT:-5433}:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data

volumes:
  postgres-data: